project/views.py
from flask import render_template, url_for, flash, redirect, Blueprint, request
from flask_login import login_user, logout_user, login_required, LoginManager
from project.app import app, db
from project.models import User, Reservation
from project.forms import ReservationForm, LoginForm, ConfirmationForm, EmailForm
from flask_mail import Mail, Message
import datetime


app_routing = Blueprint('app_routing', __name__)


mail = Mail(app)

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = "app_routing.login"
login_manager.login_message = "Zaloguj się, aby mieć dostęp do tej strony."


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


@app_routing.route('/')
def index():
    return render_template('index.html')
                           
    
@app_routing.route('/reserve', methods=['GET', 'POST'])
def reserve():
    
    form = ReservationForm()

    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data
        date = form.date.data
        time = form.time.data
        duration = form.duration.data
        numbers = form.numbers.data
        feedback = form.feedback.data
        
        new_res = Reservation(name, email, date, time, duration, numbers, feedback)
        db.session.add(new_res)
        db.session.commit()
        
        return render_template('thankyou.html', new_res=new_res)

    return render_template('reservation.html', form=form)


@app_routing.route('/admin')
@login_required
def res_list():
    result = Reservation.query.filter_by(new=True).all()
    return render_template('new_list.html', result=result)


@app_routing.route('/<int:res_id>', methods=['GET', 'POST'])
@login_required
def show(res_id):
    res = Reservation.query.get_or_404(res_id)
    
    form = ConfirmationForm()

    if form.validate_on_submit():
        confirmation = form.confirmation.data
        
        res.new = False
        res.confirmation = confirmation
        db.session.commit()

        return redirect(url_for('app_routing.res_list_conf', res=res))
    
    return render_template('single.html', res=res, form=form)


@app_routing.route('/<int:res_id>/mail', methods=['GET', 'POST'])
@login_required
def email(res_id):
    res = Reservation.query.get_or_404(res_id)
    
    form = EmailForm()
    
    if form.validate_on_submit():
        email_text = form.email_text.data
        
        res.email_text = email_text
        db.session.commit()
        
        msg = Message('Dziękujemy za zapytanie', recipients=[res.email])
        msg.cc=[msg.sender]
        msg.html = f'''<b> Witaj {res.name}! <br> Dziękujemy za zainteresowanie rezerwacją 
        Nadwiślanina w dniu {res.date} o godzinie {res.time}. <br> {res.email_text}
        <br> Pozdrawiamy - załoga Nadwiślanina. <b>'''
        mail.send(msg)
        flash('Wiadomość została wysłana!')
        
        return redirect(url_for('app_routing.show', res_id=res.id))
    
    return render_template('single_mail.html', res=res, form=form)

     
@app_routing.route('/<int:res_id>/conf')
@login_required
def show_conf(res_id):
    res = Reservation.query.get_or_404(res_id)
    return render_template('single_conf.html', res=res)


@app_routing.route('/confirmed')
@login_required
def res_list_conf():  
    today = datetime.date.today()
    result = Reservation.query.filter(Reservation.confirmation!=None, Reservation.date>today).order_by(Reservation.date).all()
    return render_template('conf_list.html', result=result)


@app_routing.route('/confirmed_old')
@login_required
def passed():  
    today = datetime.date.today()
    result = Reservation.query.filter(Reservation.confirmation!=None, Reservation.date>today).order_by(Reservation.date).all()
    old = Reservation.query.filter(Reservation.confirmation!=None, Reservation.date<today).order_by(Reservation.date).all()
    return render_template('conf_list_old.html', result=result, old=old)    


@app_routing.route('/<int:res_id>/update', methods=['GET', 'POST'])
@login_required
def update(res_id):
    res = Reservation.query.get_or_404(res_id)
    res.new = False
    db.session.commit()
    return redirect(url_for('app_routing.res_list_done', res=res))


@app_routing.route('/done')
@login_required
def res_list_done():
    result = Reservation.query.filter_by(new=False, confirmation=None).all()
    return render_template('done_list.html', result=result)


@app_routing.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Wylogowano!')
    return redirect(url_for('app_routing.index'))


@app_routing.route('/login', methods=['GET', 'POST'])
def login():

    form = LoginForm()
    
    if form.validate_on_submit():
        
        user = User.query.filter_by(username=form.username.data, 
                        password=form.password.data, is_admin=True).first()
        
        if user is not None:
    
            login_user(user)
            flash('Zalogowano!')
        
            next = request.args.get('next')

            if next == None or not next[0]=='/':
                next = url_for('app_routing.res_list')

            return redirect(next)
        
        flash('Podana nazwa użytkownika lub hasło jest niepoprawne.')
        
    return render_template('login.html', form=form)


@app_routing.app_errorhandler(404)
def error_404(error):
    return render_template('404.html'), 404

@app_routing.app_errorhandler(403)
def error_403(error):
    return render_template('403.html'), 403

project/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

    <ul class="nav">

      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('app_routing.index') }}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('app_routing.reserve') }}">Rezerwacja</a>
      </li>

      {% if current_user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('app_routing.logout') }}">Wyloguj</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('app_routing.res_list') }}">Nowe zapytania</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('app_routing.res_list_done') }}">Anulowane zapytania</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('app_routing.res_list_conf') }}">Potwierdzone zapytania</a>
      </li>

      {% endif %}

    </ul>
    <br>


  {% block content %}

  {% endblock %}


  </body>
</html>

project/templates/conf_list.html
{% extends "base.html" %}
{% block content %}

    <div class="container">

      {% with messages = get_flashed_messages() %}
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert" style="max-width: 24rem;">
              <span>{{ message }}</span>
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
              </button>
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}


      <h4>Lista potwierdzonych zapytań:</h4><br>

        {% for res in result %}
        <div class="card border-info mb-3" style="max-width: 24rem;">
          <div class="card-body">
            <div class="row">
              <div class="col-md-8">
                <h6 class="card-title"> <strong>{{res.name}}</strong></h6>
                  <ul class="card-text">
                    <li>Data: {{res.date}}</li>
                    <li>CF info: <strong>{{res.confirmation}}</strong></li>
                  </ul>
              </div>
              <div class="col-md-4">
                <a class="btn btn-info" href="{{ url_for('app_routing.show_conf', res_id=res.id) }}">Szczegóły</a>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}

        <a class="btn btn-info" href="{{ url_for('app_routing.passed') }}">Pokaż wcześniejsze</a>

        {% for o in old %}
        <div class="card border-info mb-3" style="max-width: 24rem;">
          <div class="card-body">
            <div class="row">
              <div class="col-md-8">
                <h6 class="card-title"> <strong>{{o.name}}</strong></h6>
                  <ul class="card-text">
                    <li>Data: {{o.date}}</li>
                    <li>CF info: <strong>{{o.confirmation}}</strong></li>
                  </ul>
              </div>
              <div class="col-md-4">
                <a class="btn btn-info" href="{{ url_for('app_routing.show_conf', res_id=o.id) }}">Szczegóły</a>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}


    </div>



{% endblock %}

project/templates/conf_list_old.html
{% extends "base.html" %}
{% block content %}

    <div class="container">

      {% with messages = get_flashed_messages() %}
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert" style="max-width: 24rem;">
              <span>{{ message }}</span>
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
              </button>
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}



      <h4>Lista potwierdzonych zapytań:</h4><br>

        {% for res in result %}
        <div class="card border-info mb-3" style="max-width: 24rem;">
          <div class="card-body">
            <div class="row">
              <div class="col-md-8">
                <h6 class="card-title"> <strong>{{res.name}}</strong></h6>
                  <ul class="card-text">
                    <li>Data: {{res.date}}</li>
                    <li>CF info: <strong>{{res.confirmation}}</strong></li>
                  </ul>
              </div>
              <div class="col-md-4">
                <a class="btn btn-info" href="{{ url_for('app_routing.show_conf', res_id=res.id) }}">Szczegóły</a>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}

        <br>
        <h6> Wcześniejsze: </h6>

        {% for o in old %}
        <div class="card border-info mb-3" style="max-width: 24rem;">
          <div class="card-body">
            <div class="row">
              <div class="col-md-8">
                <h6 class="card-title"> <strong>{{o.name}}</strong></h6>
                  <ul class="card-text">
                    <li>Data: {{o.date}}</li>
                    <li>CF info: <strong>{{o.confirmation}}</strong></li>
                  </ul>
              </div>
              <div class="col-md-4">
                <a class="btn btn-info" href="{{ url_for('app_routing.show_conf', res_id=o.id) }}">Szczegóły</a>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}


    </div>



{% endblock %}

project/templates/done_list.html
{% extends "base.html" %}
{% block content %}

    <div class="container">

      {% with messages = get_flashed_messages() %}
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert" style="max-width: 24rem;">
              <span>{{ message }}</span>
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
              </button>
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}


      <h4>Lista anulowanych zapytań:</h4><br>

        {% for res in result %}
        <div class="card border-info mb-3" style="max-width: 24rem;">
          <div class="card-body">
            <h6 class="card-title"> <strong>{{res.name}}</strong> --> ID: {{res.id}} </h6>
              <ul class="card-text">
                <li>Data: {{res.date}}</li>
                <li>Godzina: {{res.time}}</li>
              </ul>
          </div>
        </div>
        {% endfor %}

    </div>


{% endblock %}

project/templates/index.html
{% extends "base.html" %}
{% block content %}


    <div class="container" align="center">

      {% with messages = get_flashed_messages() %}
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert" style="max-width: 63rem;" align="left">
              <span>{{ message }}</span>
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
              </button>
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}


      <h1>WITAMY!</h1>
      <br>
      <img src="{{ url_for('static', filename='nadwislanin.jpg') }}" width="1008" height="756" >


    </div>


{% endblock %}

project/templates/login.html
{% extends "base.html" %}
{% block content %}


  <div class="container">

    {% with messages = get_flashed_messages() %}
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-danger alert-dismissible fade show" role="alert" style="max-width: 53.5rem;">
            <span>{{ message }}</span>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
            </button>
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}


    <form class="form-group" method="POST">
      {{ form.hidden_tag() }}

      <div class="row">
        <div class="col-md-4">
          <div class="form-group">
            {{ form.username.label(class="form-control-label") }}
            {{ form.username(class="form-control form-control-lg border-info mb-1") }}<br>
          </div>
        </div>
        <div class="col-md-4">
          <div class="form-group">
            {{ form.password.label(class="form-control-label") }}
            {{ form.password(class="form-control form-control-lg border-info mb-1") }}<br>
          </div>
        </div>
      </div>

      <div class="form-group">
        {{ form.submit(class="btn btn-info") }}
      </div>

    </form>
  </div>




{% endblock %}

project/templates/new_list.html
{% extends "base.html" %}
{% block content %}


    <div class="container">

      {% with messages = get_flashed_messages() %}
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert" style="max-width: 24rem;">
              <span>{{ message }}</span>
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
              </button>
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}



      <h4>Lista nowych zapytań:</h4><br>

        {% for res in result %}
        <div class="card border-info mb-3" style="max-width: 24rem;">
          <div class="card-body">
            <div class="row">
              <div class="col-md-8">
                <h6 class="card-title"> <strong>{{res.name}}</strong> --> ID: {{res.id}} </h6>
                  <ul class="card-text">
                    <li>Data: {{res.date}}</li>
                    <li>Godzina: {{res.time}}</li>
                  </ul>
              </div>
              <div class="col-md-4">
                <a class="btn btn-info" href="{{ url_for('app_routing.show', res_id=res.id) }}">Szczegóły</a>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}

    </div>






{% endblock %}

project/templates/reservation.html
{% extends "base.html" %}
{% block content %}


<div class="container">
  <h4>Prosimy o wypełnienie szczegółów zapytania:</h4><br>

  <form class="form-group" method="POST">
    {{ form.hidden_tag() }}

    <div class="row">
      <div class="col">
        <div class="form-group">
          {{ form.name.label(class="form-control-label") }}
          {{ form.name(class="form-control form-control-lg border-info mb-1") }}<br>
        </div>
      </div>
      <div class="col">
        <div class="form-group">
          {{ form.email.label(class="form-control-label") }}
          {{ form.email(class="form-control form-control-lg border-info mb-1") }}<br>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <div class="form-group">
          {{ form.date.label(class="form-control-label") }}
          {{ form.date(class="form-control form-control-lg border-info mb-1") }}<br>
        </div>
      </div>
      <div class="col">
        <div class="form-group">
          {{ form.time.label(class="form-control-label") }}
          {{ form.time(class="form-control form-control-lg border-info mb-1") }}<br>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <div class="form-group">
          {{ form.duration.label(class="form-control-label") }}
          {{ form.duration(class="form-control form-control-lg border-info mb-1") }}<br>
        </div>
      </div>
      <div class="col">
        <div class="form-group">
          {{ form.numbers.label(class="form-control-label") }}
          {{ form.numbers(class="form-control form-control-lg border-info mb-1") }}<br>
        </div>
      </div>
    </div>

        <div class="form-group">
          {{ form.feedback.label(class="form-control-label") }}
          {{ form.feedback(class="form-control form-control-lg border-info mb-1") }}<br>
        </div>
        <div class="form-group">
          {{ form.submit(class="btn btn-info") }}
        </div>
        <p> * pola wymagane </p>
  </form>

  <div align="right">

    <img src="{{ url_for('static', filename='logo.jpg') }}" width="400" height="400" >
  </div>

</div>




{% endblock %}

project/templates/single.html
{% extends "base.html" %}
{% block content %}

    <div class="container">

      {% with messages = get_flashed_messages() %}
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert" style="max-width: 40rem;">
              <span>{{ message }}</span>
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
              </button>
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}

      <h4>Szczegóły zapytania:</h4><br>
      <div class="card border-info mb-3" style="max-width: 40rem;">
        <div class="card-body">
          <div class="row">
            <div class="col">
              <h6 class="card-title"> <strong>{{res.name}}</strong> --> ID: {{res.id}} </h6>
                <ul>
                  <li>E-mail: {{res.email}}</li>
                  <li>Data: {{res.date}}</li>
                  <li>Godzina: {{res.time}}</li>
                  <li>Długość rejsu: {{res.duration}}</li>
                  <li>Liczba osób: {{res.numbers}}</li>
                  <li>Info: {{res.feedback}}</li>
                </ul>
            </div>
            <div class="col">
              <a class="btn btn-info" href="{{ url_for('app_routing.update', res_id=res.id) }}">Anulowane</a>

              <form class="form-group" method="POST">
                {{ form.hidden_tag() }}
                <br>
                <div class="form-group">
                  {{ form.confirmation.label(class="form-control-label") }}
                  {{ form.confirmation(class="form-control form-control-lg") }}<br>
                </div>
                <div class="form-group">
                  {{ form.submit(class="btn btn-info") }}
                </div>
              </form>
            </div>
          </div>

        </div>
      </div>

      <a class="btn btn-info" href="{{ url_for('app_routing.email', res_id=res.id) }}">Utwórz wiadomość e-mail</a>



    </div>





{% endblock %}

project/templates/single_conf.html
{% extends "base.html" %}
{% block content %}

<div class="container">

  {% with messages = get_flashed_messages() %}
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert" style="max-width: 28rem;">
          <span>{{ message }}</span>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
          </button>
        </div>
      {% endfor %}
    {% endif %}
  {% endwith %}



  <h4>Szczegóły zapytania:</h4><br>
  <div class="card border-info mb-3" style="max-width: 28rem;">
    <div class="card-body">
      <div class="row">
        <div class="col-md-8">
          <h6 class="card-title"> <strong>{{res.name}}</strong> --> ID: {{res.id}} </h6>
            <ul>
              <li>E-mail: {{res.email}}</li>
              <li>Data: {{res.date}}</li>
              <li>Godzina: {{res.time}}</li>
              <li>Długość rejsu: {{res.duration}}</li>
              <li>Liczba osób: {{res.numbers}}</li>
              <li>Info: {{res.feedback}}</li>
            </ul>
        </div>
        <div class="col-md-4">
          <p> <strong>{{res.confirmation}}</strong> </p>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

project/templates/single_mail.html
{% extends "base.html" %}
{% block content %}

    <div class="container">

      {% with messages = get_flashed_messages() %}
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert" style="max-width: 40rem;">
              <span>{{ message }}</span>
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
              </button>
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}


      <h4>Szczegóły zapytania:</h4><br>
      <div class="card border-info mb-3" style="max-width: 40rem;">
        <div class="card-body">
          <div class="row">
            <div class="col">
              <h6 class="card-title"> <strong>{{res.name}}</strong> --> ID: {{res.id}} </h6>
                <ul>
                  <li>E-mail: {{res.email}}</li>
                  <li>Data: {{res.date}}</li>
                  <li>Godzina: {{res.time}}</li>
                  <li>Długość rejsu: {{res.duration}}</li>
                  <li>Liczba osób: {{res.numbers}}</li>
                  <li>Info: {{res.feedback}}</li>
                </ul>
            </div>
          </div>

          <div class="row">
            <form class="form-group" method="POST">
              {{ form.hidden_tag() }}
              <br>
              <div class="form-group">
                {{ form.email_text.label(class="form-control-label") }}
                {{ form.email_text(class="form-control form-control-lg") }}<br>
              </div>
              <div class="form-group">
                {{ form.submit(class="btn btn-info") }}
              </div>
            </form>

          </div>
        </div>
      </div>


    </div>





{% endblock %}

project/templates/thankyou.html
{% extends "base.html" %}
{% block content %}

    <div class="container">
      <div align='center'>
        <h2>Witaj {{new_res.name}}!</h2>
        <h4>Dziękujemy za zainteresowanie rezerwacją Nadwiślanina</h4>
        <h4>w dniu <strong>{{new_res.date}}</strong> o godzinie <strong>{{new_res.time}}</strong>.</h4>
        <h6>Sprawdzimy możliwość zorganizowania rejsu i prześlemy szczegóły
          na podany adres email: <em>{{new_res.email}}</em>.</h6>
        <br>
        <img src="{{ url_for('static', filename='logo_bw.jpg') }}" width="390.5" height="397" >

      </div>
    </div>



{% endblock %}